### PR TITLE
[WIP] Add ORAS exclusive moves.

### PR DESCRIPTION
**Pull request by Cu3PO42**
I scraped the learnsets for Pokémon in ORAS from Serebii and added them to the db with the new `version_group`.

### CODE REVIEW

**Comment by RichardGottschalk** [comment]
I think you should also add the changes from versions.csv, version_names.csv, version_groups.csv and all the other versions related .csv files

**Comment by Cu3PO42** [comment]
I'm sorry, I'm not sure what you mean. I based this on `origin/oras`, hence changes made there to include the new versions are 'included'. The only thing I can see concerning versions that may be unhandled is in `version_group_move_methods`. I did not yet add the move methods that are available in ORAS, but I shall do so ASAP.

**Comment by Cu3PO42** [comment]
Misses the moves that are completely new in ORAS, i.e. Dragon's Ascent, etc.

Thought those were already in the branch, but it was the new abilities.

**Comment by codemonkey85** [comment]
@Cu3PO42 @magical If you guys need data ripped from ORAS (as opposed to scraping it or manually entering it), have you asked anyone at Project Pokémon if they have the data handy? I'm sure Kaphotics or someone would be willing to contribute.

**Comment by Cu3PO42** [comment]
@codemonkey85 I haven't asked specifically, but scraping was like a 20 line job and it seemed to be the easiest thing. I might ask or have a look at my own decrypted copy though, if I need more data.

**Comment by codemonkey85** [comment]
@Cu3PO42 The only thing that concerns me about scraping data from any website is the reliance that the data was flawlessly entered into said website.

**Comment by Cu3PO42** [comment]
@codemonkey85 That's a valid concern. Though I'm not specifically worried about Serebii due to high traffic of the site and ORAS being released for quite some time. Maybe he even got the data from the game. When I have any more time I will probably double check with the learnsets from the ROM. (And add the three missing moves...)

**Comment by RichardGottschalk** [comment]
Is there any example/tutorial on how to rip data directly from the game? I think this is the main problem here...
If more people would know how to do this the data would be more consistent, accurate and up-to-date. And then we do not have to copy data from other websites...

I would really like to rip some data but don't know anything about how to use python or this script.

**Comment by encukou** [comment]
@Cu3PO42 Veekun has traditionally has data scraped from games whenever feasible, which means Serebii/Bulbapedia have more data (and faster), but of lower quality. (High traffic doesn't matter for obscure moves -- why would anyone check the exact level for Remoraid to learn Hydro Pump?)

@RichardGottschalk Unfortunately, ripping data is a bit of an art and requires specific background knowledge. (It could, however make a nice blog post, maybe when @eevee starts running out of topics to blog about...)

**Comment by Cu3PO42** [comment]
@encukou Alright, I'll have a look at a few GARCs when I have the time and fix mistakes or just confirm the data is right. Thanks for providing insight about the best practices here.

**Comment by eevee** [comment]
This has now been ripped directly, but thanks regardless  :)

**Pull request closed without merging**
