### PR TITLE
Add official color codes of each type and damage class

### PR DESCRIPTION
**Pull request by phmatray**

### CODE REVIEW

**Comment by phmatray** [comment]
Hello @eevee 
I've used the color codes from the type images into the pokedex_media repository.
[Here is a look](https://scontent-amt2-1.xx.fbcdn.net/v/t1.0-9/14203323_10209601775456424_8835813899497280358_n.jpg?oh=50604f0ea02144173030ecfdc87bf6f2&oe=58482E30)

**Comment by eevee** [comment]
Ah, that's an interesting idea.

Why ARGB and not just RGB, though?  I don't think an alpha channel really makes sense for these colors.  (Also every time I've seen an 8-hexit color, it's been RGBA.)

**Comment by magical** [comment]
That's cool, i guess.
1. Why ARGB instead of RGB? All the colors are opaque.
2. These should not be UnicodeText
3. How "official" are these colors really? The type icons we have are from gen V iirc. Other games have used different colors. The fairy type icon we straight-up fabricated.

**Comment by RichardGottschalk** [comment]
I have never seen a RGBA notation for colors. It was always ARGB or RGB...
but I don't think the alpha canal is important for those colors. So I'm for RGB :)

In my project I write the type name over a background with a given type color.
Some colors are just too dark to write with black text color over it. So I made a separated field to indicate dark colors.
Those dark colors are chosen manually and are used to invert the text colors.
Do you need this, too?

**Comment by eevee** [comment]
Hm, probably not — that's the kind of thing I would figure out on the fly in code, since it's not canonically from the games.

I'm curious about the cross-gen issue, though.  Maybe this warrants a separate table also keyed on version group.

**Comment by phmatray** [comment]
Perhaps there is need for further analysis.
Should we give up for now?

**Comment by metaunicorn** [comment]
This is a good idea but I also agree that the RGB format is more appropiate and that we also need a separated table for it, because each generation use to have different colors.

We also have to consider that in some generation 2 colors have been used (like red and blue for the Dragon type) and gradients of 2 colors like in Gen 6.

**Comment by magical** [comment]
I would rather add all the type icons to pokedex-media than add a table containing all the colors to the database. Anyone who needs the colors can get them from the icons.

**Comment by FarbodSalamat-Zadeh** [comment]
I agree with @magical and @metaunicorn here.

Color codes can definitely be useful, so I think what @phmatray is doing is an interesting idea; however, I'm concerned that it's not the best since the icons have gradients in their backgrounds, and also that there are different colors for different versions.

**Comment by eevee** [comment]
Ah, I forgot about the split dragon sprite.

I'm +0 on this — I like the general idea, but you'd have to find some very robust way to express these cases for it to really be useful.

**Comment by phmatray** [comment]
OK, forget that idea.
I think that we can close this issue without merging.
Thanks for all your comments :)

**Pull request closed without merging**
