### PR TITLE
Update versions.csv

### PR DESCRIPTION
**Pull request by adrianodennanni**

### CODE REVIEW

**Comment by eevee** [comment]
i suspect doing this without actually loading any of the data will fill the website with a bunch of empty space (or, break it entirely)

**Comment by magical** [comment]
Like eevee said, there's no point in doing this before the rest of the data is added.

**Comment by RichardGottschalk** [comment]
is there a way to add the OR AS data?

**Comment by remyjette** [comment]
Unfortunately the 3DS carts are encrypted so it's not possible to do a direct dump of the game data like it was for previous versions. For X/Y and now OR/AS it had/has to be done manually which takes time.

**Comment by Josephvb10** [comment]
Actually, it's very possible and relatively fast.  Serebii does it every time a game comes out for his Pokédex. Project Pokémon will provide the data if they are asked for it, I'm pretty sure they will contribute.

**Comment by remyjette** [comment]
It's true, at this point many others have done the work and could probably provide the data for this project. But that's why it couldn't happen right when OR/AS was released.

**Comment by codemonkey85** [comment]
I'm sure Project Pokémon would willingly contribute what they have, but @eevee already knows how to contact us when the time comes.

**Comment by antialiasis** [comment]
I had the impression the main reason the OR/AS data isn't up was just that Zhorken left veekun and nobody's stepped up to fill the vacuum they left.

**Comment by magical** [comment]
Pretty much.

**Pull request closed without merging**
