### PR TITLE
Added some missing translations

### PR DESCRIPTION
**Pull request by RichardGottschalk**
Some translations for version names, region names, encunter method proses and a type.
Also fixed the german translation of AS version name

### CODE REVIEW

**Comment by Ketsuban** [comment]
That's rough terrain, as found [in Kalos on Route 9](http://veekun.com/dex/locations/route%209).

**Comment by RichardGottschalk** [comment]
ok, I see. This looks like a combination of several new ground types. I will add a matching german translation

**Comment by RichardGottschalk** [comment]
-.- I wanted to add it as quickly as possible and just copied the english line without replacing the local_language_id. I'm sorry!

**Comment by magical** [comment]
Looks good to me. Thanks for the patch!

**Comment by magical** [comment]
I find it ironic that the region whose name means "unity" has so many different translations.

**Pull request merged**
