### PR TITLE
added pokedexes for Sun/Moon and Ultrasun/Ultramoon

### PR DESCRIPTION
**Pull request by nitwhiz**
for #217 
used bulbapedia as source, alolan forms are used instead of their normal forms in species_id

### CODE REVIEW

**Comment by magical** [comment]
> alolan forms are used instead of their normal forms in species_id

It doesn't work like that. `species_id` has to point to a row in the `pokemon_species` table, which only contains species, not forms.

Doesn't Alola have four separate dexes?

**Comment by thechief389** [comment]
I suggest you add another column called "pokemon_form_id", so that you can get the species and the particular form of that pokémon.

**Comment by magical** [comment]
We can't merge this unless the `species_id`s are fixed. Closing.

**Comment by magical** [comment]
Oh, i just noticed that codedmonkey submitted an alternative PR, https://github.com/veekun/pokedex/pull/269.  I'll probably end up merging that one.

**Pull request closed without merging**
