### PR TITLE
Added USUM Tutor Moves. Serebii is source.

### PR DESCRIPTION
**Pull request by lunemily**

### CODE REVIEW

**Comment by magical** [comment]
Usually we prefer to rip data from a primary source rather than a secondary source like Serebii.

**Comment by evanfuhr** [comment]
What constitutes a primary source? Is there an approved list I could use?

**Comment by magical** [comment]
The best source is usually the ROMs themselves.

**Comment by magical** [comment]
These were added in #331. Thanks though. Sorry it took so long.

**Pull request closed without merging**
