### PR TITLE
Generation 2 (GSC) encounters

### PR DESCRIPTION
**Pull request by Rogerooo**
**Source**: https://www.pokebip.com/page/jeuxvideo/dossier_shasse/encounter_slot

This covers the following encounter methods:  _Walking, Fishing (3 rods), Surf and Rock Smash_

**Some observations:** 
1. I decided not to add the _[Bug Catching Contest](https://bulbapedia.bulbagarden.net/wiki/Bug-Catching_Contest)_ Pokémons has I'm not quite sure if they need a new encounter condition or not. There are only 12 for each version so it's not too much trouble to add them later.

2.  If i'm not mistaken, there are 2 location_areas missing. I haven't created the records for them because I'm not yet familiarized with the database indices and location_areas make use of them. The areas are the following:

- [Olivine City Harbor](https://bulbapedia.bulbagarden.net/wiki/Olivine_City) (location_id: 85), there are unique Pokémon encounters from the main city for fishing and surfing in the harbor. Checking the Bulbapedia page I can see that only in gen 2 there is a difference in encounters, HGSS does not make a distinction between the areas and that's possibly why the area hasn't been added yet.

- [Mt. Silver Chambers](https://bulbapedia.bulbagarden.net/wiki/Mt._Silver) (location_id: 82), I'm not sure what is supposed to be the area id for the chambers. They are located on 2F and contain an item each. Even though the encounters for the versions Gold and Silver are essentially the same as 2F, they are not for Crystal (where only Golbat, Parasect and Misdreavus appear as opposed to Golbat, Parasect, Misdreavus, Golduck, Machoke, Ursaring and Larvitar of 2F)

3. Unfortunately there is no information about Headbutt encounter method on the source's tables. Those encounters will have to be added with other sources data.

### CODE REVIEW

**Comment by route1rodent** [comment]
I am not in favor of adding data from websites, we don't know what are their source.
We'd better get real game data for this, like from the disassembled games: https://github.com/pret
but this requires scripting techniques and programming skills.

**Comment by magical** [comment]
> HGSS does not make a distinction between the areas and that's possibly why the area hasn't been added yet

Yeah that would be why. Location areas are created as-needed.

> I haven't created the records for them because I'm not yet familiarized with the database indices and location_areas make use of them. 

If you're referring to `location_areas.game_index`, you can just set it to 0. It's not really important. (It's important for some tables. Not this one.)

> Mt. Silver Chambers (location_id: 82), I'm not sure what is supposed to be the area id for the chambers. 

If there's no suitable location area yet, you can add whatever area(s) you need.

**Comment by magical** [comment]
> I am not in favor of adding data from websites, we don't know what are their source.

While i agree in principle, gen 2 encounters have been missing for so long, and the source looks likely enough to be accurate (in my estimation), that i'm willing to merge this as a stopgap. I'm sure we will re-rip them at some point.

**Comment by route1rodent** [comment]
@magical do you know if the ripping scripts are available somewhere?

**Comment by magical** [comment]
@route1rodent ripping scripts for what? GSC encounters?

obviously we haven't written a script to extract GSC encounters yet. maybe someone else has. i do have this old script that meowth346 wrote: https://turnipmints.mooo.com/~andrew/pokemon/wild.gbc.zip

other scripts for other games and other types of data are floating around in various places. it's all a bit of a mess.

**Comment by route1rodent** [comment]
@magical I was wondering if there was some work already started that we can continue, even if it's not related to encounters, but at least an initial script to parse data from G/S/C.

I was thinking about doing that with the pret disassembles: https://github.com/pret/pokegold/tree/master/data/wild

**Comment by magical** [comment]
> I was thinking about doing that with the pret disassembles: https://github.com/pret/pokegold/tree/master/data/wild

Unfortunately pokegold hasn't gotten to the point of disassembling the encounter tables yet. If you look closely, you'll see that those are actually the encounters from crystal.

**Comment by route1rodent** [comment]
oh pity. I guess after all it will be easier to have this added manually like @Rogerooo has done
and we'll apply fixes if needed at some point

**Pull request merged**
