### PR TITLE
Update Aegislash stats

### PR DESCRIPTION
**Pull request by tesu**

### CODE REVIEW

**Comment by magical** [comment]
Was this the only stat change in gen 8? We should probably update them all at once, along with adding the rest of the gen 8 data (#284).

**Comment by tesu** [comment]
Yes, this was the only stat change in gen 8. I confirmed this on [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Aegislash_(Pok%C3%A9mon)#Trivia) and [Serebii](https://www.serebii.net/swordshield/updatedstats.shtml).

**Comment by magical** [comment]
Great, thanks for checking.

It still feels weird to me to make piecemeal changes like this. I don't want to be in a situation where some data is from one gen and some is from another -- it's inconsistent. But this is so minor maybe it would be okay.

**Comment by chamander** [comment]
Poor old Aegislash getting a nerf? That's a shame... I'm unfamiliar with the schema, only ever glancing at [various](https://veekun.github.io/pokedex/main-tables.html) bits of [explanations](https://eev.ee/blog/2016/08/05/storing-pokémon-without-sql/), so I wish there were ways to store the data for each generation, but I agree with not liking a situation where the information is only accurate for a particular generation. In case this is merged here, and then some other species' stats are updated from a separate generation, the data wouldn't be completely accurate for _any_ generation...

**Pull request closed without merging**
