### PR TITLE
Fix FR/LG Duplicate Locations

### LINKED ISSUE #103: Fix FRLG encounters
Everybody disagreed with me about how location areas should work.

### LINKED ISSUE #156: separation in location area encounters
I'm sure this isn't an issue at all but I'm hoping to clear something up. I've been working quite a bit on V2 of [Pokeapi](https://github.com/phalt/pokeapi) which is making heavy use of the data here (which is fantastic).

I've been working on wrapping my head around encounters and how they relate to location areas and have noticed a "separation" in how they're stored in the db. For example in Cerulean Cave I've noticed multiple entries for the same area.
```
323,147,140,1f
324,147,141,2f
325,147,142,b1f
...
472,147,24,1f
473,147,25,2f
474,147,26,b1f
```
After digging deeper I've noticed the areas 323-325 relate to encounters in R, B, Y, HG, and SS and the areas 472-474 relate only to encounters in FR and LG.

Is there a clear reason for this separation? Is this just due to how the data has evolved over time? Why would they not all be grouped together? Am I reading too far into this? AM I LOSING MY MIND!? HALP!

### PR DESCRIPTION
**Pull request by seii**
* Fixes #103 
* Fixes #156 

Special thanks to @magical , as his notes in 103 were invaluable for several merges and cleanups

PLEASE check this for accuracy. It touches lots of "location" and "location_area" numbers, as well as their children. My testing so far seems to say that I got all the references I should have, but as a newcomer to this schema I can't be certain.

### CODE REVIEW

**Comment by magical** [comment]
Thanks for working on this!

I got the following error when trying to load the database into postgres

```
location_area_encounter_rates...                                     
Traceback (most recent call last):
  File "/home/andrew/veekun/bin/pokedex", line 9, in <module>
    load_entry_point('Pokedex==0.1', 'console_scripts', 'pokedex')()
  File "/home/andrew/veekun/pokedex/pokedex/main.py", line 27, in setuptools_entry
    main(*sys.argv)
  File "/home/andrew/veekun/pokedex/pokedex/main.py", line 23, in main
    args.func(parser, args)
  File "/home/andrew/veekun/pokedex/pokedex/main.py", line 249, in command_load
    langs=langs,
  File "/home/andrew/veekun/pokedex/pokedex/db/load.py", line 235, in load
    csvfile,
psycopg2.IntegrityError: insert or update on table "location_area_encounter_rates" violates foreign key c
onstraint "location_area_encounter_rates_location_area_id_fkey"
DETAIL:  Key (location_area_id)=(468) is not present in table "location_areas".
```

**Comment by seii** [comment]
Ah, you found some encounter rates that I missed during the Safari Zone migration! This update should fix it, please let me know if you see other problems.

**Comment by magical** [comment]
Looks good to me. There was a little mixup with the floors of the Pokémon Mansion but i've fixed it locally. I didn't look too closely at location_area_encounter_rates, but i'll assume they're correct.

**Comment by magical** [comment]
And merged. Thanks again.

**Pull request merged**
